### ISSUE TITLE
Backend Routes - Due 6/13

### ISSUE THREAD

**Issue by cjc473** [shannale/Shaphora#5]
# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by cjc473** [comment]
Remaining changes:

1. In products, change the index route from chirps to products (lol)
2. Remove the GET request from cart items. Since we already have a GET request to the current user, we can use a user.cart_items association to bring their cart_items into the redux store. 
3. Remote the GET index request from reviews for the same reason above. We can either get a collection of reviews through the current_user.reviews or product.reviews. You can leave the GET show request for reviews, since you'll probably use that route for your edit form.

**Comment by shannale** [comment]
o m g not the chirps

**Comment by cjc473** [comment]
Done!
